version: "3.6"

services:
  httpd-base:
    image: "${REGISTRY}/${APP_NAMESPACE}/httpd-base:${CI_COMMIT_REF_NAME-latest}"
    build:
      context: ./
      dockerfile: ../../../docker/httpd/Dockerfile
      args:
        REGISTRY: ${REGISTRY}
        USER_UID: ${LOCAL_UID}
        USER_NAME: ${LOCAL_USERNAME}

  php-base:
    image: "${REGISTRY}/${APP_NAMESPACE}/php-base:${CI_COMMIT_REF_NAME-latest}"
    build:
      context: ./
      dockerfile: ../../../docker/php/Dockerfile
      args:
        REGISTRY: ${REGISTRY}
        USER_UID: ${LOCAL_UID}
        USER_NAME: ${LOCAL_USERNAME}

  node-base:
    image: "${REGISTRY}/${APP_NAMESPACE}/node-base:${CI_COMMIT_REF_NAME-latest}"
    build:
      context: ../../../
      dockerfile: docker/node/Dockerfile
      args:
        REGISTRY: ${REGISTRY}
        USER_UID: ${LOCAL_UID}
        USER_NAME: ${LOCAL_USERNAME}